language: c

cache:
  directories:
    - tundra
    - vbcc

addons:
  apt:
    packages:
      - p7zip-full

before_install:
  - export PATH=$PATH:$PWD/tundra/bin
  - export VBCC=$PWD/vbcc

install:
  - if [ ! -f tundra/bin/tundra2 ]; then git clone --recurse-submodules https://github.com/deplinenoise/tundra.git t2-build && cd t2-build && make -j 4 && PREFIX=$PWD/../tundra make install && cd - ; fi
  - if [ ! -f vbcc/bin/vbccm68k ]; then ./build_vbcc.sh ; fi

script:
  - tundra2 release
  - tundra2 -j 1 amiga-vbcc-release
